project_id = "ojbwbbqmqxyxwwujzokm"

[functions.japanese-chat]
verify_jwt = false

[functions.process-video]
verify_jwt = false

[functions.lookup-word]
verify_jwt = false

[functions.generate-reading]
verify_jwt = false

[functions.fetch-youtube-captions]
verify_jwt = false

[functions.japanese-analysis]
verify_jwt = false

[functions.japanese-grammar]
verify_jwt = false

[functions.kanji-details]
verify_jwt = false

[functions.kanji-related]
verify_jwt = false

[functions.kanji-search]
verify_jwt = false

[functions.generate-video-quiz]
verify_jwt = false

[functions.generate-grammar-quiz]
verify_jwt = false
