/**
 * Re-export of the Supabase generated database types so both apps can import
 * from `@lex-love-loom/types/supabase` instead of touching the raw FE-managed file.
 *
 * The actual `Database` type lives in `src/integrations/supabase/types.ts` and is
 * regenerated by Lovable Cloud. Do NOT edit that file by hand.
 */
export type { Database } from "../../../src/integrations/supabase/types";
