import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';

dotenv.config({ path: path.resolve(process.cwd(), '.env') });

const supabaseUrl = process.env.VITE_SUPABASE_URL || '';
const supabaseKey = process.env.VITE_SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';
const supabase = createClient(supabaseUrl, supabaseKey);

const GROQ_API_KEY = process.env.GROQ_API_KEY_1 || process.env.GROQ_API_KEY_2;

// The themes of Minna no Nihongo lessons to guide the AI
const lessonThemes: Record<number, string> = {
  1: 'Self-introduction, countries, professions',
  2: 'Demonstratives (kore, sore), office/everyday items',
  3: 'Places, directions, prices',
  4: 'Time, days of the week, daily routines',
  5: 'Transportation, dates, going places',
  6: 'Transitive verbs, food, daily activities',
  7: 'Tools, languages, giving/receiving',
  8: 'Adjectives, describing things and places',
  9: 'Preferences, abilities, reasons',
  10: 'Existence (arimasu, imasu), locations',
  11: 'Counters, periods, frequency',
  12: 'Past tense of adjectives/nouns, comparisons',
  13: 'Desires (hoshii, -tai), purpose of going',
  14: 'Te-form, requests, progressive actions',
  15: 'Permissions, prohibitions, current states',
  16: 'Sequential actions, descriptions using Te-form',
  17: 'Nai-form, obligations (nakereba narimasen)',
  18: 'Dictionary form, abilities, experiences',
  19: 'Ta-form, past experiences, alternating actions',
  20: 'Plain forms (casual speech)',
  21: 'Expressing opinions, quoting',
  22: 'Noun modifiers (relative clauses)',
  23: 'Conditionals (toki, to)',
  24: 'Giving and receiving (kuremasu, agemasu)',
  25: 'Conditionals (tara, temo)',
  26: 'Seeking/giving explanations (ndesu)',
  27: 'Potential verbs',
  28: 'Simultaneous actions (nagara), habitual actions',
  29: 'Intransitive verbs, states (te-imasu)',
  30: 'Preparation (te-okimasu)',
  31: 'Volitional form, intentions',
  32: 'Advice (hou ga ii), predictions (deshou)',
  33: 'Imperative and prohibitive forms',
  34: 'Quoting exactly, doing actions exactly as shown',
  35: 'Conditionals (ba-form)',
  36: 'Efforts and habits (you ni shimasu)',
  37: 'Passive verbs',
  38: 'Nominalization (no, koto)',
  39: 'Reasons using Te-form',
  40: 'Embedded questions (ka, kadouka)',
  41: 'Giving/receiving with respect (itadakimasu, kudasaimasu)',
  42: 'Purpose (tame ni), use',
  43: 'Appearance (sou desu), excessive actions',
  44: 'Ease/difficulty of actions, combining verbs',
  45: 'Cases and conditions (baai, noni)',
  46: 'Points in time (tokoro)',
  47: 'Hearsay (sou desu)',
  48: 'Causative verbs',
  49: 'Respectful language (Sonkeigo)',
  50: 'Humble language (Kenjougo)'
};

async function generateExtraVocab(lessonNumber: number, theme: string) {
  const prompt = `You are a Japanese linguistics expert. Generate EXACTLY 20 extra, highly relevant "Reference Words" (参考語彙) and Expressions for Minna no Nihongo Lesson ${lessonNumber}.
The theme of this lesson is: ${theme}.
These words should NOT be the basic core vocabulary (like watashi, anata) but rather related vocabulary (e.g. if the lesson is about professions, provide 20 extra professions like architect, programmer, etc).
Include nouns, verbs, or adjectives relevant to the theme.

Return the result STRICTLY as a JSON array of objects with this format:
[
  { "word": "Kanji or word", "reading": "hiragana reading", "meaning_vi": "Vietnamese meaning" }
]
DO NOT output any markdown, explanations, or code blocks. Just the raw JSON array.`;

  try {
    const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${GROQ_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: 'llama-3.3-70b-versatile',
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.3
      })
    });
    
    if (!res.ok) throw new Error(`Groq API error: ${res.statusText}`);
    const data = await res.json();
    let text = data.choices[0].message.content.trim();
    
    // Clean potential markdown formatting
    if (text.startsWith('```')) {
      text = text.replace(/^```(json)?\n?/, '').replace(/\n?```$/, '');
    }
    
    const words = JSON.parse(text);
    return words;
  } catch (err) {
    console.error(`Failed to generate for lesson ${lessonNumber}`, err);
    return [];
  }
}

async function run() {
  console.log('--- Generating Enhanced Minna no Nihongo Vocabulary ---');
  let finalSql = `-- Enhanced Reference Vocabulary for Minna no Nihongo\n-- Generated by AI Agent to expand lessons >50 words\n\n`;
  
  // To avoid hitting rate limits too hard, we do 5 lessons to prove the concept and give the user an immediate massive boost. If the user wants all 50, we can run a full batch.
  // For this run, we'll augment the first 10 lessons as an immediate powerful upgrade.
  const startLesson = 11;
  const lessonsToAugment = 50; 

  for (let i = startLesson; i <= lessonsToAugment; i++) {
    console.log(`Generating 20 extra words for Lesson ${i}: ${lessonThemes[i]}`);
    const extras = await generateExtraVocab(i, lessonThemes[i]);
    
    if (extras.length > 0) {
      finalSql += `\n-- Lesson ${i} Extra Vocabulary\n`;
      finalSql += `INSERT INTO vocabulary_master (textbook_id, lesson_id, jlpt_level, word, reading, furigana, meaning_vi)\n`;
      finalSql += `SELECT t.id, l.id, 'N5', v.word, v.reading, v.reading, v.meaning_vi\n`;
      finalSql += `FROM textbooks t JOIN lessons l ON l.textbook_id = t.id AND l.lesson_number = ${i}\n`;
      finalSql += `CROSS JOIN (VALUES\n`;
      
      const values = extras.map((w: any) => {
          const word = (w.word || '').replace(/'/g, "''");
          const reading = (w.reading || '').replace(/'/g, "''");
          const meaning = (w.meaning_vi || '').replace(/'/g, "''");
          return `  ('${word}', '${reading}', '${meaning}')`;
      });
      
      finalSql += values.join(',\n');
      finalSql += `\n) AS v(word, reading, meaning_vi)\n`;
      finalSql += `WHERE t.name = 'Minna no Nihongo'\n`;
      finalSql += `ON CONFLICT (textbook_id, word, reading) DO NOTHING;\n\n`;
      
      // Update word count for the lesson natively
      finalSql += `UPDATE lessons l\nSET word_count = (SELECT COUNT(*) FROM vocabulary_master WHERE lesson_id = l.id)\n`;
      finalSql += `FROM textbooks t\nWHERE l.textbook_id = t.id AND t.name = 'Minna no Nihongo' AND l.lesson_number = ${i};\n`;
    }
    
    // Slight delay to respect rate limits
    await new Promise(r => setTimeout(r, 1000));
  }

  const outPath = 'C:\\Users\\Pheo\\.gemini\\antigravity\\brain\\afc46569-4ad8-433c-8685-3e0ce6b739c3\\minna_enhanced_vocab.sql';
  fs.appendFileSync(outPath, finalSql);
  console.log(`--- Generation Complete: saved to ${outPath} ---`);
}

run();
